FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel
RUN apt-get update
RUN apt-get install -y vim git
RUN DEBIAN_FRONTEND=oninteractive apt-get install -y wget unzip python3-virtualenv
RUN python3 -m pip install --upgrade pip

RUN apt-get install -y libgl1-mesa-glx
RUN apt-get install -y libglib2.0-0
RUN pip install numpy matplotlib overboard einops torch-scatter numba tensorboard torchvision torchaudio pyglet==1.5 pandas mat4py opencv-contrib-python scipy

WORKDIR /work


